{
 "title": "Ceph Pool Details",
 "tags": [ "ceph-mixin" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(ceph_osd_metadata{}, job)"
    }
   },
   {
    "name": "pool_name",
    "label": "Pool Name",
    "query": {
     "query": "label_values(ceph_pool_metadata{job=~\"$job\"}, name)"
    }
   },
   {
    "name": "pool_type",
    "label": "Pool Type",
    "query": {
     "query": "label_values(ceph_pool_metadata{job=~\"$job\", name=\"$pool_name\"},type)"
    }
   },
   {
    "name": "pool_profile",
    "label": "Pool Profile",
    "query": {
     "query": "label_values(ceph_pool_metadata{job=~\"$job\", name=\"$pool_name\"},description)"
    }
   },
   {
    "name": "pool_id",
    "label": "Pool ID",
    "query": {
     "query": "label_values(ceph_pool_metadata{job=~\"$job\", name=\"$pool_name\"},pool_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Capacity used",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (name) ((ceph_pool_stored{job=~\"$job\"} / (ceph_pool_stored{job=~\"$job\"} + ceph_pool_max_avail{job=~\"$job\"})) *\n  on(pool_id) group_left(name) ceph_pool_metadata{job=~\"$job\", name=~\"$pool_name\"})\n"
    }
   ]
  },
  {
   "title": "Available space for new objects in pool",
   "type": "stat",
   "description": "Until quota (or overall limit) is reached and writes become blocked.",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (ceph_pool_quota_bytes{job=~\"$job\"} - ceph_pool_stored{job=~\"$job\"}) * on(pool_id) group_left(name) ceph_pool_metadata{job=~\"$job\", name=~\"$pool_name\"} and on(pool_id) (ceph_pool_quota_bytes{job=~\"$job\"} > 0)\n)\nor\n(\n  ceph_pool_max_avail{job=~\"$job\"} * on(pool_id) group_left(name) ceph_pool_metadata{job=~\"$job\", name=~\"$pool_name\"} and on(pool_id) (ceph_pool_quota_bytes{job=~\"$job\"} <= 0)\n)"
    }
   ]
  },
  {
   "title": "$pool_name object ingress/egress",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "max by (pool_id) (deriv(ceph_pool_objects{job=~\"$job\"}[1m])) *\n  on(pool_id) group_left(name) ceph_pool_metadata{job=~\"$job\", name=~\"$pool_name\"}\n",
     "legendFormat": "Objects per second"
    }
   ]
  },
  {
   "title": "$pool_name client IOPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "max by (pool_id) (rate(ceph_pool_rd{job=~\"$job\"}[$__rate_interval])) *\n  on(pool_id) group_left(name) ceph_pool_metadata{job=~\"$job\", name=~\"$pool_name\"}\n",
     "legendFormat": "reads"
    },
    {
     "expr": "max by (pool_id) (rate(ceph_pool_wr{job=~\"$job\"}[$__rate_interval])) *\n  on(pool_id) group_left(name) ceph_pool_metadata{job=~\"$job\", name=~\"$pool_name\"}\n",
     "legendFormat": "writes"
    }
   ]
  },
  {
   "title": "$pool_name client throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "max by (pool_id) (rate(ceph_pool_rd_bytes{job=~\"$job\"}[$__rate_interval])) +\n  on(pool_id) group_left(name) ceph_pool_metadata{job=~\"$job\", name=~\"$pool_name\"}\n",
     "legendFormat": "reads"
    },
    {
     "expr": "max by (pool_id) (rate(ceph_pool_wr_bytes{job=~\"$job\"}[$__rate_interval])) +\n  on(pool_id) group_left(name) ceph_pool_metadata{job=~\"$job\", name=~\"$pool_name\"}\n",
     "legendFormat": "writes"
    }
   ]
  },
  {
   "title": "$pool_name total objects",
   "type": "timeseries",
   "description": "And object quota if set",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (pool_id) (ceph_pool_objects{job=~\"$job\"}) *\n  on(pool_id) group_left(name) ceph_pool_metadata{job=~\"$job\", name=~\"$pool_name\"}",
     "legendFormat": "Number of Objects"
    },
    {
     "expr": "(ceph_pool_quota_objects{job=~\"$job\"} > 0) * on(pool_id) group_left(name) ceph_pool_metadata{job=~\"$job\", name=~\"$pool_name\"}",
     "legendFormat": "Object Quota"
    }
   ]
  },
  {
   "title": "$pool_name size (logical)",
   "type": "timeseries",
   "description": "Ceph pool data usage (logical - before replication/erasure coding) and quota (if set)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (pool_id) (ceph_pool_stored{job=~\"$job\"}) *\n  on(pool_id) group_left(name) ceph_pool_metadata{job=~\"$job\", name=~\"$pool_name\"}",
     "legendFormat": "{{name}} logical storage used"
    },
    {
     "expr": "(ceph_pool_quota_bytes{job=~\"$job\"} > 0) * on(pool_id) group_left(name) ceph_pool_metadata{job=~\"$job\", name=~\"$pool_name\"}",
     "legendFormat": "{{name}} pool quota"
    }
   ]
  },
  { "title": "Physical storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "$pool_name size (physical)",
   "type": "timeseries",
   "description": "Ceph pool physical storage",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(ceph_pool_bytes_used{job=~\"$job\", pool_id=~\"$pool_id\"})",
     "legendFormat": "$pool_name pool, $pool_type ($pool_profile)"
    }
   ]
  }
 ]
}